#!/bin/bash
set -e

echo "╔═══════════════════════════════════════════════════════════╗"
echo "║          Workforce Platform - Deployment Script           ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo ""

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# ============================================================================
# REQUIRED ENVIRONMENT VARIABLES
# ============================================================================
#
# For LOCAL development, create a .env file in the project root with:
#
# # Supabase (https://supabase.com/dashboard/project/cydhvvqvgrvntzitrrwy/settings/api)
# SUPABASE_PROJECT=cydhvvqvgrvntzitrrwy
# SUPABASE_ANON_KEY=eyJ...  (anon public key)
# SUPABASE_SERVICE_KEY=eyJ...  (service_role key)
#
# # Database (https://supabase.com/dashboard/project/cydhvvqvgrvntzitrrwy/settings/database)
# DATABASE_URL=postgresql://postgres.cydhvvqvgrvntzitrrwy:<password>@aws-1-ap-south-1.pooler.supabase.com:6543/postgres
#
# # AI Provider (https://openrouter.ai/keys)
# OPENROUTER_API_KEY=sk-or-v1-...
# DEFAULT_MODEL=google/gemini-3-pro-preview
#
# ============================================================================
# PRODUCTION URLS
# ============================================================================
#
# Frontend (Vercel): https://workforce.dooza.ai
# Backend (Render):  https://workforce-api-g3kg.onrender.com
# Health Check:      https://workforce-api-g3kg.onrender.com/health
#
# ============================================================================

# Load .env file if it exists
if [ -f ".env" ]; then
  echo -e "${CYAN}Loading .env file...${NC}"
  export $(grep -v '^#' .env | xargs)
fi

# Configuration - Load from .env or environment
SUPABASE_PROJECT="${SUPABASE_PROJECT:-cydhvvqvgrvntzitrrwy}"
SUPABASE_URL="https://${SUPABASE_PROJECT}.supabase.co"
DEFAULT_MODEL="${DEFAULT_MODEL:-google/gemini-3-pro-preview}"

# Check required environment variables
MISSING_VARS=""
[ -z "$SUPABASE_ANON_KEY" ] && MISSING_VARS="$MISSING_VARS\n  - SUPABASE_ANON_KEY (from Supabase Dashboard > Settings > API)"
[ -z "$SUPABASE_SERVICE_KEY" ] && MISSING_VARS="$MISSING_VARS\n  - SUPABASE_SERVICE_KEY (from Supabase Dashboard > Settings > API)"
[ -z "$DATABASE_URL" ] && MISSING_VARS="$MISSING_VARS\n  - DATABASE_URL (from Supabase Dashboard > Settings > Database)"
[ -z "$OPENROUTER_API_KEY" ] && MISSING_VARS="$MISSING_VARS\n  - OPENROUTER_API_KEY (from https://openrouter.ai/keys)"

if [ -n "$MISSING_VARS" ]; then
  echo -e "${RED}Error: Missing required environment variables${NC}"
  echo -e "$MISSING_VARS"
  echo ""
  echo "Create a .env file in the project root with these values."
  echo "See DEPLOYMENT.md for detailed instructions."
  exit 1
fi

cd "$(dirname "$0")"
ROOT_DIR=$(pwd)

echo -e "${YELLOW}[1/6] Creating directories...${NC}"
mkdir -p /tmp/workforce-tenants
echo -e "${GREEN}Done${NC}"

echo ""
echo -e "${YELLOW}[2/6] Creating platform/.env...${NC}"
cat > "$ROOT_DIR/platform/.env" << EOF
# Workforce Platform Backend Environment
# Generated by deploy.sh - DO NOT COMMIT

# Server
PORT=3000
NODE_ENV=development
TENANT_DATA_DIR=/tmp/workforce-tenants

# Supabase
SUPABASE_URL=$SUPABASE_URL
SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY
SUPABASE_SERVICE_KEY=$SUPABASE_SERVICE_KEY

# Database
DATABASE_URL=$DATABASE_URL

# AI Provider
OPENROUTER_API_KEY=$OPENROUTER_API_KEY
DEFAULT_MODEL=$DEFAULT_MODEL
EOF
echo -e "${GREEN}Done${NC}"

echo ""
echo -e "${YELLOW}[3/6] Creating platform/web/.env...${NC}"
cat > "$ROOT_DIR/platform/web/.env" << EOF
# Workforce Platform Frontend Environment
# Generated by deploy.sh - DO NOT COMMIT

VITE_SUPABASE_URL=$SUPABASE_URL
VITE_SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY
# For local dev, API calls go through Vite proxy to localhost:3000
# VITE_API_URL is only needed for production (set in Vercel)
EOF
echo -e "${GREEN}Done${NC}"

echo ""
echo -e "${YELLOW}[4/6] Installing dependencies...${NC}"
cd "$ROOT_DIR/platform" && pnpm install --silent
cd "$ROOT_DIR/platform/web" && pnpm install --silent
echo -e "${GREEN}Done${NC}"

echo ""
echo -e "${YELLOW}[5/6] Pushing database schema...${NC}"
cd "$ROOT_DIR/platform"
DATABASE_URL="$DATABASE_URL" pnpm db:push 2>&1 | grep -E "(Changes|✓|Error)" || echo "Schema up to date"
echo -e "${GREEN}Done${NC}"

echo ""
echo -e "${YELLOW}[6/6] Starting servers...${NC}"
# Kill existing processes
lsof -ti:3000 | xargs kill -9 2>/dev/null || true
lsof -ti:5173 | xargs kill -9 2>/dev/null || true
lsof -ti:5174 | xargs kill -9 2>/dev/null || true
sleep 1

# Start API server
cd "$ROOT_DIR/platform"
pnpm dev > /tmp/workforce-api.log 2>&1 &
API_PID=$!

# Start web frontend
cd "$ROOT_DIR/platform/web"
pnpm dev > /tmp/workforce-web.log 2>&1 &
WEB_PID=$!

sleep 5
echo -e "${GREEN}Servers started${NC}"

echo ""
echo -e "${YELLOW}Checking status...${NC}"
if curl -s http://localhost:3000/health | grep -q "ok"; then
  echo -e "${GREEN}✓ API Server: Running on http://localhost:3000${NC}"
else
  echo -e "${RED}✗ API Server: Not responding${NC}"
fi

WEB_PORT=$(grep -oE "localhost:[0-9]+" /tmp/workforce-web.log | head -1 | cut -d: -f2)
if [ -n "$WEB_PORT" ]; then
  echo -e "${GREEN}✓ Web Frontend: Running on http://localhost:${WEB_PORT}${NC}"
else
  echo -e "${YELLOW}○ Web Frontend: Starting...${NC}"
fi

echo ""
echo "╔═══════════════════════════════════════════════════════════╗"
echo "║                    LOCAL DEV READY                        ║"
echo "╠═══════════════════════════════════════════════════════════╣"
echo "║                                                           ║"
echo "║  Local URLs:                                              ║"
echo "║  - Frontend: http://localhost:5173                        ║"
echo "║  - Backend:  http://localhost:3000                        ║"
echo "║  - Health:   http://localhost:3000/health                 ║"
echo "║                                                           ║"
echo "╠═══════════════════════════════════════════════════════════╣"
echo "║                                                           ║"
echo "║  Production URLs:                                         ║"
echo "║  - Frontend: https://workforce.dooza.ai                   ║"
echo "║  - Backend:  https://workforce-api-g3kg.onrender.com      ║"
echo "║                                                           ║"
echo "╠═══════════════════════════════════════════════════════════╣"
echo "║                                                           ║"
echo "║  Configuration:                                           ║"
echo "║  - Supabase: $SUPABASE_URL             ║"
echo "║  - AI Model: $DEFAULT_MODEL (via OpenRouter)  ║"
echo "║  - Database: Connected                                    ║"
echo "║                                                           ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo ""
echo "View logs:"
echo "  API: tail -f /tmp/workforce-api.log"
echo "  Web: tail -f /tmp/workforce-web.log"
echo ""
echo "For deployment docs, see: DEPLOYMENT.md"
echo ""
